//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 10:56:57 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:10302/0302-ws-javaconfig-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.reos;
